# Generated by Django 2.2.6 on 2019-11-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('tag_name',)},
        ),
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, upload_to='question_photo'),
        ),
    ]
