# Generated by Django 2.2.6 on 2019-11-15 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191103_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, to='questions.Tag'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='datetime_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, default='baran.jpg', upload_to='question_photo'),
        ),
    ]
